---
- name: Ensuring HAProxy is deployed
  hosts: all
  become: true
  tasks:
    - name: Ensure HAProxy is installed
      dnf:
        name: haproxy
        state: latest

    - name: Enabled Haproxy service
      service:
        name: haproxy
        state: started
        enabled: true

    - name: Configuring Haproxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
